---
sidebar: sidebar 
permalink: get-started/prerequisites-ontap-update.html 
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions, prepare for ontap update 
summary: Reveja os pré-requisitos e requisitos antes de prosseguir com a atualização do ONTAP. 
---
= Prepare-se para atualizar o ONTAP usando as atualizações de software do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve rever os pré-requisitos e requisitos antes de prosseguir com a atualização do ONTAP. Você pode usar as atualizações de software do BlueXP  para verificar a prontidão do seu ambiente operacional, login, acesso à rede e navegador da Web.

.Função BlueXP necessária:
Administrador da organização, administrador de pasta ou projeto, administrador de armazenamento, visualizador de armazenamento ou especialista em integridade do sistema. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do BlueXP."^]

Para usar as atualizações de software do BlueXP , você deve garantir que seu ambiente atenda a todos os requisitos.

* Um ambiente de trabalho é configurado no BlueXP .
* As credenciais de administrador estão disponíveis para o cluster desejado durante a atualização de software.
* Todos os nós no cluster estão enviando dados AutoSupport.
* Todos os nós devem ser executados no ONTAP 9.10 ou versões posteriores.
* Os nós não devem estar em uma configuração MetroCluster.

